# traefik.yml

# Global log level
log:
  level: INFO

# API and Dashboard
api:
  insecure: true
  dashboard: true

# Metrics (Prometheus)
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true

# Entrypoints
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":9100"

# Providers
providers:
  docker:
    exposedByDefault: false
    network: traefik-proxy

# Certificate Resolvers are not needed for an HTTP-only setup
# but we leave the empty section so Traefik doesn't error if referenced.
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
