# traefik.yml

## Global Logging
log:
  level: INFO

## API & Dashboard
api:
  dashboard: true
  insecure: true

## Metrics (Prometheus)
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true

## Entrypoints
entryPoints:
  web:
    address: "${TRAEFIK_ENTRYPOINTS_WEB_ADDRESS}"
  websecure:
    address: "${TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS}"
  metrics:
    address: "${TRAEFIK_ENTRYPOINTS_METRICS_ADDRESS}"
  traefik:
    address: "${TRAEFIK_ENTRYPOINTS_TRAEFIK_ADDRESS}"

## Providers
providers:
  docker:
    endpoint: "${TRAEFIK_PROVIDERS_DOCKER_ENDPOINT}"
    exposedByDefault: ${TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT}
    network: "${TRAEFIK_PROVIDERS_DOCKER_NETWORK}"
  file:
    filename: /etc/traefik/redirect.yml
    watch: true

## Certificate Resolvers (Let's Encrypt)
certificatesResolvers:
  letsencrypt:
    acme:
      email: "${TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL}"
      storage: "${TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE}"
      httpChallenge:
        entryPoint: "${TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE_ENTRYPOINT}"
